download:
  conf_file: ''
  download_option: download_clean
  output_dir: ''
  password: ''
  subfolder: RELECOV
  user: ''
validate:
  excel_sheet: ''
  json_file: ''
  json_schema_file: relecov_tools/schema/relecov_schema.json
  metadata: ''
  output_dir: ''
