name: test_wrapper_sftp

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches: "**"

concurrency:
  group: ${{ github.repository }}-test_wrapper
  cancel-in-progress: false
  
jobs:
  test_sftp_handle_new:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        download_options: ["download_only", "download_clean", "delete_only"]
        target_folders: ["-t COD-test-1"]
      
    steps:
    - name: Set up Python 3.9.16
      uses: actions/setup-python@v3
      with:
        python-version: '3.9.16'
      
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
      
    - name: Install package and dependencies
      run: |
        pip install -r requirements.txt
        pip install .
      
    - name: Run sftp_handle tests
      run: |
        python3 tests/test_sftp_handle.py --download_option ${{ matrix.download_options }} ${{ matrix.target_folders }}
      env:
        TEST_USER: ${{ secrets.TEST_USER }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        TEST_PORT: ${{ secrets.TEST_PORT }}
        OUTPUT_LOCATION: ${{ github.workspace }}/tests/


  test_wrapper:
    runs-on: ubuntu-latest
    needs: test_sftp_handle_new
    strategy:
      max-parallel: 1
      matrix:
        download_options: ["download_only", "download_clean"]
        target_folders: ["-t COD-test-1"]
        modules: ["wrapper"]
            
    steps:
    - name: Set up Python 3.9.16
      uses: actions/setup-python@v3
      with:
        python-version: '3.9.16'

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
            
    - name: Install package and dependencies
      run: |
        pip install -r requirements.txt
        pip install .

    - name: Debug environment variables
      run: |
        echo "TEST_USER=${{ secrets.TEST_USER }}"
        echo "TEST_PORT=${{ secrets.TEST_PORT }}"
      env:
        TEST_USER: ${{ secrets.TEST_USER }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        TEST_PORT: ${{ secrets.TEST_PORT }}
      
      
    - name: Run Wrapper tests
      run: |
        python3 tests/test_wrapper_handle.py --download_option ${{ matrix.download_options }} ${{ matrix.target_folders }}
      env:
        TEST_USER: ${{ secrets.TEST_USER }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        TEST_PORT: ${{ secrets.TEST_PORT }}
        OUTPUT_LOCATION: ${{ github.workspace }}/tests/
        